### ISSUE TITLE
Dockerize

### ISSUE THREAD

**Issue by vsoch** [robinsloan/sentencespace#3]
hey @robinsloan ! I saw your post and played around with the web application, and this is so great! I'm working on Dockerizing this for you (since the dependency base is a little funky!) and I was hoping you might be able to help by providing me as much version info for the various modules that you can. Usually if you do a pip freeze, e.g.,

```
pip freeze
```
with the active environment where the application works, it will spit out a nice list. I had originally thought I'd port everything to python 3, but looking at the changes in theano I'm going to first start with the version that you have. The second bit is that there seems to be be hard coded paths to model files in some of the json objects:

```
grep -R /home/robin
session/sp15_trial/hyper_params.json:{"vocab": "vocab.pkl", "max_len": 128, "lstm_size": 1000, "p": 0.0, "alpha": 0.3, "sp_model": "/home/robin/dev/water-margin/sp/sf256.model", "z": 128, "dataset": "scifi-plus-gutenberg.txt"}
```
If you might be able to do a grep and then (even just tell me here) I'll be able to fix everything up. I'm creating a base docker image (Dockerfile) and then a compose file to add the nginx webserver, to (likely) keep running with gunicorn.

**Comment by richardassar** [comment]
Awesome. Thanks for Dockerizing

**Comment by robinsloan** [comment]
Hey @vsoch! This is a cool idea. I don't use Docker, but I know a lot of folks do.

Here's the output from `conda list` in the environment I'm using -- which is not exclusively for `sentence-space` so there's some cruft in here:

```
better-exceptions         0.2.1                     <pip>
cairo                     1.14.8                        0  
certifi                   2017.4.17                 <pip>
cffi                      1.10.0                   py27_0  
chardet                   3.0.3                     <pip>
click                     6.7                      py27_0  
cuda80                    1.0                           0    soumith
cycler                    0.10.0                   py27_0  
cython                    0.26                     py27_0  
dbus                      1.10.10                       0  
expat                     2.1.0                         0  
flask                     0.12.2                   py27_0  
fontconfig                2.12.1                        3  
freetype                  2.5.5                         2  
functools32               3.2.3.2                  py27_0  
future                    0.16.0                   py27_1  
glib                      2.50.2                        1  
gst-plugins-base          1.8.0                         0  
gstreamer                 1.8.0                         0  
gunicorn                  19.1.0                   py27_0  
h5py                      2.7.0               np112py27_0  
hdf5                      1.8.17                        1  
icu                       54.1                          0  
idna                      2.5                       <pip>
itsdangerous              0.24                     py27_0  
jbig                      2.1                           0  
jinja2                    2.9.6                    py27_0  
jpeg                      9b                            0  
libffi                    3.2.1                         1  
libgcc                    5.2.0                         0  
libgfortran               3.0.0                         1  
libgpuarray               0.6.4                         0  
libiconv                  1.14                          0  
libpng                    1.6.27                        0  
libtiff                   4.0.6                         3  
libxcb                    1.12                          1  
libxml2                   2.9.4                         0  
mako                      1.0.6                    py27_0  
markupsafe                0.23                     py27_2  
matplotlib                2.0.2               np112py27_0  
mkl                       2017.0.1                      0  
mkl-service               1.1.2                    py27_3  
msgpack-python            0.4.8                     <pip>
nnmnkwii                  0.0.3.dev0                <pip>
nose                      1.3.7                    py27_1  
numpy                     1.12.1                   py27_0  
olefile                   0.44                     py27_0  
opencv                    2.4.11                 nppy27_0    menpo
openssl                   1.0.2l                        0  
pandas                    0.20.1              np112py27_0  
pastalog                  1.0.3                     <pip>
pastedeploy               1.5.2                    py27_1  
pcre                      8.39                          1  
pillow                    4.1.1                    py27_0  
pip                       9.0.1                    py27_1  
pixman                    0.34.0                        0  
pyaudio                   0.2.7                    py27_1    mutirri
pycairo                   1.10.0                   py27_0  
pycparser                 2.17                     py27_0  
pygpu                     0.6.4                    py27_1  
pyparsing                 2.1.4                    py27_0  
pyqt                      5.6.0                    py27_2  
python                    2.7.13                        0  
python-cjson              1.2.1                     <pip>
python-dateutil           2.6.0                    py27_0  
pytorch                   0.1.12               py27_2cu80  [cuda80]  soumith
pytorch-extras            0.1.3                     <pip>
pytz                      2017.2                   py27_0  
PyYAML                    3.12                      <pip>
qt                        5.6.2                         4  
readline                  6.2                           2  
requests                  2.17.3                    <pip>
scipy                     0.19.0              np112py27_0  
sentencepiece             0.0.0                     <pip>
setuptools                27.2.0                   py27_0  
sip                       4.18                     py27_0  
six                       1.10.0                   py27_0  
sklearn                   0.0                       <pip>
sqlite                    3.13.0                        0  
subprocess32              3.2.7                    py27_0  
theano                    0.9.0                    py27_0  
tk                        8.5.18                        0  
torchvision               0.1.8                    py27_2    soumith
urllib3                   1.21.1                    <pip>
werkzeug                  0.12.2                   py27_0  
wheel                     0.29.0                   py27_0  
wordfilter                0.2.6.2                   <pip>
xz                        5.2.2                         1  
zlib                      1.2.8                         3
```

As for that absolute path: it's now included in the project, in the `sp_models` directory, but I forgot to update everything else to reflect that. What do you suppose the best way to reference it from the `hyper_params.json` in a given session's directory is? Will `../sp_models/sf256.model` work okay, or is there some other more robust way to do it?

**Comment by vsoch** [comment]
awesome thank you! The relative path fix is good and the model loads okay now. As long as this is baked into a container and we can be relatively confident that relative paths won't change, this should do the trick!  And I've updated the path in my branch so don't worry about needing to do fixes.

I need to debug a few data type errors that are jumping out (that I think are likely just a wrong version).  One more question - do you have anything in a file at `~/.theanorc` ?

**Comment by robinsloan** [comment]
Yes indeed:

```
[global]
floatX = float32
device = gpu0
optimizer_including=cudnn

[cuda]
root = /usr/local/cuda-7.5
```

**Comment by vsoch** [comment]
Great! That's what I needed!

And to answer your question, the most robust way (when you have multiple files) usually comes down to:

 - figuring out how to reduce the number of files, period.
 - keeping files with dependencies in the same directory, so at least they are carried in the same folder
 - and of course using containers (preferably read only) so it's baked, `*`forever!

and then you can have fallbacks to check / alert if things are missing...  overall the general spirit is to "do your best" because it's hard. 

*until somone unbakes it :)

**Comment by robinsloan** [comment]
That's helpful to hear -- thanks!

**Comment by vsoch** [comment]
Well installation of nvidia / cuda (as you know) is highly erroneous and gross, so let's not get our hopes up too early that this will work to easily install in a container!

**Comment by robinsloan** [comment]
"Gross" is right! I have a bunch of environments that I'm afraid to even _look_ at the wrong way, for fear they will suddenly and inexplicably collapse into a tangle of version mismatches. ✨Godspeed!✨

**Comment by vsoch** [comment]
okay the nvidia is somewhat working, and now your code doesn't work with it. The error I'm hitting is:

```
loaded deconv_bn3_inv_std
loaded deconv_bn2_mean
loaded deconv_bn2_inv_std
loaded deconv_bn1_mean
loaded deconv_bn1_inv_std
Traceback (most recent call last):
  File "textproject_server.py", line 84, in <module>
    from_z = decoder_from_z(x) #sampled.astype(theano.config.floatX))
  File "/code/nn/containers.py", line 11, in __call__
    x = layer(x)
  File "/code/nn/layers1d.py", line 183, in __call__
    conved = dnn.dnn_conv(image, w, subsample=(self.stride, 1), border_mode=(self.pad, 0))
  File "/usr/local/miniconda/lib/python2.7/site-packages/theano/gpuarray/dnn.py", line 1077, in dnn_conv
    ctx_name = infer_context_name(img, kerns)
  File "/usr/local/miniconda/lib/python2.7/site-packages/theano/gpuarray/basic_ops.py", line 127, in infer_context_name
    raise ValueError("Could not infer context from inputs")
ValueError: Could not infer context from inputs
root@47610c118fc8:/code# 
```
Is this meaningful to you? The function is here, and it seems like a mess:

https://github.com/Theano/Theano/blob/master/theano/gpuarray/basic_ops.py#L101

I tried updating to not rely on cdnn and this was huge, because most of us humans don't have GPUs sitting around... 

https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end%28gpuarray%29

So the issue is, as it usually is, all of the mixture of things on your host combined with old versions of things (who can keep up) so Im not able to reproduce your exact enivronment. I think if I had more experience with theano I could debug the error, so I'm hoping you or others have some insight to how to specify the context (I couldn't figure out).

**Comment by vsoch** [comment]
Note that for the above we change the input from the old cnn dependency to `theano.gpuarray.dnn`

I just opened up a work in progress (WIP) PR so we can have a clear log of changes to discuss!

https://github.com/vsoch/sentencespace/pull/1/files

**Comment by robinsloan** [comment]
I don't know much about Theano, old or new -- I was working around it more than I was working with it.

In case it's helpful: on the `sentence-space` server, I just created a new environment from scratch, building it like this --

```
conda create -n sentence-space-test python=2.7
source activate sentence-space-test
conda install flask
conda install numpy=1.12.1
conda install theano=0.9.0
conda install pandas=0.20.1
conda install matplotlib=2.0.2

pip install wordfilter
pip install sentencepiece
```

-- and then got the server running cleanly, as well as the training script. So it looks like that's the minimum required environment, absent any Theano changes/upgrades.

**Comment by vsoch** [comment]
yes the difference is actually the server - I'm building this isn't a docker container and I don't have any idea about what your server looks like, beyond the basic versions. There are dependencies that theano needs such as GPU (or not) along with even what version of conda you are doing. I will rebuild with those exact versions (and I think I already tried) but until we can reproduce the working config in a Docker container, it's no go.

**Comment by vsoch** [comment]
I am assuming there are some nvidia libraries installed? Which ones?

**Comment by robinsloan** [comment]
Got it. I'm out of my depth here -- I don't think I even know Docker containers could access the GPU! Brave new world! But yeah, I'm running all of this with CUDA 7.5 and cudnn 5.1.

And I always ignored the "Please switch to the gpuarray" messages because... I could 😈

**Comment by vsoch** [comment]
haha yeah :) Well unfortunately it means the work isn't reproducible, so we should figure this out. I'm not sure I can put more time into it today (I've already spent about 6 hours) but hopefully others interested will pick up. I htink the key is choosing the right docker image base, I chose one I know provided by nvidia that will come with the needed libraries:

https://github.com/vsoch/sentencespace/pull/1/files#diff-3254677a7917c6c01f55212f86c57fbfR1

but likely there is conflict between all these different versions. The end lesson I think is that for projects like these that use bleeding edge stuffs, it's good to start work off the bat (meaning writing your original scripts)  already within a contained environment where you have selected versions and tested dependencies. Otherwise it turns into a "work backwards and hope someone can reverse engineer it."

**Comment by vsoch** [comment]
Actually I'm starting to think that the model itself was likely compiled or built in an enviornment that cannot load it - can you provide the script to build the model from scratch? I bet you the bug is trickling down from that, because I can't load the model to begin with:

```
python textproject_server.py 
Loaded vocab with 258 chars:
sentencepiece_processor.cc(42) LOG(WARNING) Cannot open sf256.model
Loading session sp15_trial
Trained using dataset sp15_trial
```

**Comment by robinsloan** [comment]
Hmm I wonder if you need the sentencepiece libraries in addition to the Python module? I thought I'd used the module on its own before, but maybe not. It's easy to install -- see google/sentencepiece.

I should upload a different model that was trained _without_ sentencepiece to make some of this complexity optional. I'll do that later when I'm in front of my computer!

**Comment by vsoch** [comment]
okay sounds good! If we can start from a slightly more simple base, then it might make easier the rest of the debugging. I'll be back later too!

**Comment by vsoch** [comment]
okay I'm trying the build again - the only tiny difference would be the protobug libarires, which I think are for serializing to different formats so maybe that will do the trick to fix loading the model!

**Comment by vsoch** [comment]
okay the error about loading the model is gone - tiny step closer! I'm going to go back and try the (deprecated) approach, just in case there is hope there, haha.

**Comment by vsoch** [comment]
I don't know much more how I can help - I cannot reverse engineer your setup. This is also incredibly important for reproducibility... the work can never be extended, used, or reproduced if it is not portable. I think, if this is important for you, it would be logical to start with the first steps you took to build the model, but do it *starting* from a portable enviroinment (e.g., one of the nvidia-docker containers if you want to use gpu / cuda and all that stuff). --> https://hub.docker.com/r/nvidia/cuda/tags/

You could start there, go through your setup and development steps (hopefully not too hard since you did it previously?) and then have your container ready to go! WIthout knowing all the details of your environment the most I (or anyone) could do is guess and (hope to) stumble on a working thing. 

And if you don't want to invest the time, that's ok too :) But next time you start a new project, maybe? Definitely please ping me if I can help out! :)

**Comment by eyaler** [comment]
This is really important. I am currently facing performance issue in training. specifically, i see a x2 slowdown when using theano 1.0 over 0.9. i am currently investigating effect of cuda, cudnn versions as my setup still seems slower by an order of magnitude...

**Comment by vsoch** [comment]
yeah, this is unfortunately the reality we face because these technologies change so rapidly! The thing you run locally (with some complex set of installs) doesn't reproduce... the next day! My strategy has been trying to simplify things as much as possible.

**Comment by LanceNorskog** [comment]
Is the Dockerization project finished, or in a functioning state?

**Comment by vsoch** [comment]
We need a way for @robinsloan to provide the exact set of libraries versions, etc. that were used, because the current "out of the box" that I put together didn't seem to do the trick. @robinsloan have you made any progress on this? I'd be glad to help with just a little bit more guidance in this respect. See my comment from https://github.com/robinsloan/sentence-space/issues/3#issuecomment-370540735

**Comment by LanceNorskog** [comment]
@vsoch @robinsloan As Theano is an end-of-life technology base, I found a VAE written in Keras and ported it to Google Colab. This one simplifies the problem by limiting it to 10-word sentences. 
I used a limited text set (descriptions of images) for the training text. If you load into Colab, hit GO and come back in a couple of hours, it should finish. It's not ready for deployment as a packaged useable toy. I've adopted a slightly different end goal for my research (generating iambic pentameter) and have done this as a side thing to explore NLP.
Cheers!

https://github.com/LanceNorskog/vae/blob/master/vae_nlp__mscoco.ipynb

**Comment by vsoch** [comment]
This is great! There is hope! Are you able to do a ! pip freeze to show all the versions of the modules that you are  using? That would make it much easier to try and reproduce the work building a container.

Happy New Year!
